/** Declaration file generated by dts-gen */

declare module 'js-object-tools' {
  function check(val: any, type: any): any;
  function isPlainObject(obj: any): any;
  namespace diff {
  function $addToSet(dest: any, src: any): any;
  function $set(dest: any, source: any): any;
  function $unset(dest: any, source: any): any;
  function allKeyPaths(obj: any): any;
  function any(iterable: any, fn: any): any;
  function apply(dest: any, source: any): any;
  function arrayify(val: any): any;
  function clone(input: any): any;
  function combine(... args: any[]): any;
  function contains(set: any, match: any): any;
  function containsAll(set: any, match: any): any;
  function containsAny(set: any, match: any): any;
  function diffToModifier(prev: any, doc: any, fieldsToIgnore?: any,
                          pruneEmptyObjects?: any): any;
  function every(iterable: any, fn: any): any;
  function extend(target: any, source: any): any;
  function filteredKeyPaths(_keyPaths: any, ignore: any): any;
  function flatObject(object: any, options: any): any;
  function forwardDiffToModifier(prev: any, doc: any, fieldsToIgnore: any): any;
  function groupReduce(objOrArray: any, groupField: any, reduceFunction: any,
                       baseType: any): any;
  function keyPathContainsPath(keyPath: any, ignorePath: any): any;
  function keyPaths(obj: any, _options: any, _stack: any, parent: any): any;
  function mapModifierToKey(modifier: any, key: any): any;
  function mergeValueAtKeypath(value: any, keyPath: any, obj: any): any;
  function modifierToObj(modifier: any): any;
  function objToModifier(obj: any): any;
  function okmap(iterable: any, fn: any): any;
  function prune(obj: any): any;
  function setValueForKeyPath(value: any, keyPath: any, input: any): void;
  function stringify(json: any, rep?: any[], ind?: any): any;
  function unsetKeyPath(keyPath: any, obj: any): any;
  function update(doc: any, options: any): any;
  function valueForKeyPath(keyPath: any, input: any): any;
  }
}