/** Declaration file generated by dts-gen */

declare module 'dependency-graph' {
  class DepGraph {
    [index: string]: any;
    addDependency(parent: string, node: string): void;
    addNode(name: string): void;
  }
}