#!/bin/bash
APP=$1
if [ $APP ]
then
  pm2 delete devops/local/stateful.yaml --only $APP
  pm2 delete devops/local/services.yaml --only $APP
else
pm2 delete devops/local/services.yaml
pm2 delete devops/local/stateful.yaml
fi
